//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketAdvisor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TicketAdvisor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Érkezési állomás (vissza).
        /// </summary>
        internal static string DetailView_DetailView_BackArriveStation {
            get {
                return ResourceManager.GetString("DetailView_DetailView_BackArriveStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Érkezési idő (vissza).
        /// </summary>
        internal static string DetailView_DetailView_BackArriveTime {
            get {
                return ResourceManager.GetString("DetailView_DetailView_BackArriveTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indulási dátum (vissza).
        /// </summary>
        internal static string DetailView_DetailView_BackStartDate {
            get {
                return ResourceManager.GetString("DetailView_DetailView_BackStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Induló állomás (vissza).
        /// </summary>
        internal static string DetailView_DetailView_BackStartStation {
            get {
                return ResourceManager.GetString("DetailView_DetailView_BackStartStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indulási idő (vissza).
        /// </summary>
        internal static string DetailView_DetailView_BackStartTime {
            get {
                return ResourceManager.GetString("DetailView_DetailView_BackStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Átszállások (vissza).
        /// </summary>
        internal static string DetailView_DetailView_BackStops {
            get {
                return ResourceManager.GetString("DetailView_DetailView_BackStops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utazási idő (vissza).
        /// </summary>
        internal static string DetailView_DetailView_BackTravelTime {
            get {
                return ResourceManager.GetString("DetailView_DetailView_BackTravelTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kereső neve:.
        /// </summary>
        internal static string DetailView_DetailView_EngineName {
            get {
                return ResourceManager.GetString("DetailView_DetailView_EngineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kereső neve:.
        /// </summary>
        internal static string DetailView_DetailView_Kereső_neve_ {
            get {
                return ResourceManager.GetString("DetailView_DetailView_Kereső_neve_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Érkezési állomás (oda).
        /// </summary>
        internal static string DetailView_DetailView_OutArriveStation {
            get {
                return ResourceManager.GetString("DetailView_DetailView_OutArriveStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Érkezési idő (oda).
        /// </summary>
        internal static string DetailView_DetailView_OutArriveTime {
            get {
                return ResourceManager.GetString("DetailView_DetailView_OutArriveTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cég (oda).
        /// </summary>
        internal static string DetailView_DetailView_OutCompany {
            get {
                return ResourceManager.GetString("DetailView_DetailView_OutCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indulási dátum (oda).
        /// </summary>
        internal static string DetailView_DetailView_OutStartDate {
            get {
                return ResourceManager.GetString("DetailView_DetailView_OutStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Induló állomás (oda).
        /// </summary>
        internal static string DetailView_DetailView_OutStartStation {
            get {
                return ResourceManager.GetString("DetailView_DetailView_OutStartStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indulási idő (oda).
        /// </summary>
        internal static string DetailView_DetailView_OutStartTime {
            get {
                return ResourceManager.GetString("DetailView_DetailView_OutStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Átszállások (oda).
        /// </summary>
        internal static string DetailView_DetailView_OutStops {
            get {
                return ResourceManager.GetString("DetailView_DetailView_OutStops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utazási idő (oda).
        /// </summary>
        internal static string DetailView_DetailView_OutTravelTime {
            get {
                return ResourceManager.GetString("DetailView_DetailView_OutTravelTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ár/fő.
        /// </summary>
        internal static string DetailView_DetailView_PerPrice {
            get {
                return ResourceManager.GetString("DetailView_DetailView_PerPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ár.
        /// </summary>
        internal static string DetailView_DetailView_Price {
            get {
                return ResourceManager.GetString("DetailView_DetailView_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cég (vissza).
        /// </summary>
        internal static string DetailView_DetailView_RetCompany {
            get {
                return ResourceManager.GetString("DetailView_DetailView_RetCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Átszállások:.
        /// </summary>
        internal static string DetailView_DetailView_Stops {
            get {
                return ResourceManager.GetString("DetailView_DetailView_Stops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Összár:.
        /// </summary>
        internal static string DetailView_DetailView_SumPrice {
            get {
                return ResourceManager.GetString("DetailView_DetailView_SumPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jegyek száma:.
        /// </summary>
        internal static string DetailView_DetailView_TicketCount {
            get {
                return ResourceManager.GetString("DetailView_DetailView_TicketCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Útidő.
        /// </summary>
        internal static string DetailView_DetailView_TravelTime {
            get {
                return ResourceManager.GetString("DetailView_DetailView_TravelTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utazási idő (oda).
        /// </summary>
        internal static string DetailView_DetailView_TravelTimeOut {
            get {
                return ResourceManager.GetString("DetailView_DetailView_TravelTimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hazaút.
        /// </summary>
        internal static string Form1_Form1_Load_BackDate {
            get {
                return ResourceManager.GetString("Form1_Form1_Load_BackDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gyerekek.
        /// </summary>
        internal static string Form1_Form1_Load_Children {
            get {
                return ResourceManager.GetString("Form1_Form1_Load_Children", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Csecsemők.
        /// </summary>
        internal static string Form1_Form1_Load_Infants {
            get {
                return ResourceManager.GetString("Form1_Form1_Load_Infants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiutazás.
        /// </summary>
        internal static string Form1_Form1_Load_OutDate {
            get {
                return ResourceManager.GetString("Form1_Form1_Load_OutDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kész.
        /// </summary>
        internal static string Form1_resultCheck_Tick_Kész {
            get {
                return ResourceManager.GetString("Form1_resultCheck_Tick_Kész", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leállítva.
        /// </summary>
        internal static string Form1_resultCheck_Tick_Stopped {
            get {
                return ResourceManager.GetString("Form1_resultCheck_Tick_Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keresés....
        /// </summary>
        internal static string MainForm_btnSearch_Click_Searching {
            get {
                return ResourceManager.GetString("MainForm_btnSearch_Click_Searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leállít.
        /// </summary>
        internal static string MainForm_btnSearch_Click_Stop {
            get {
                return ResourceManager.GetString("MainForm_btnSearch_Click_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hozzáad.
        /// </summary>
        internal static string MainForm_MainForm_Load_Add {
            get {
                return ResourceManager.GetString("MainForm_MainForm_Load_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Felnőtt.
        /// </summary>
        internal static string MainForm_MainForm_Load_Adult {
            get {
                return ResourceManager.GetString("MainForm_MainForm_Load_Adult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Felnőttek.
        /// </summary>
        internal static string MainForm_MainForm_Load_Adults {
            get {
                return ResourceManager.GetString("MainForm_MainForm_Load_Adults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TicketAdvisor.
        /// </summary>
        internal static string MainForm_MainForm_Load_AppName {
            get {
                return ResourceManager.GetString("MainForm_MainForm_Load_AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vissza.
        /// </summary>
        internal static string MainForm_MainForm_Load_BackDate {
            get {
                return ResourceManager.GetString("MainForm_MainForm_Load_BackDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gyerek.
        /// </summary>
        internal static string MainForm_MainForm_Load_Children {
            get {
                return ResourceManager.GetString("MainForm_MainForm_Load_Children", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dátum.
        /// </summary>
        internal static string MainForm_MainForm_Load_Date {
            get {
                return ResourceManager.GetString("MainForm_MainForm_Load_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Töröl.
        /// </summary>
        internal static string MainForm_MainForm_Load_Delete {
            get {
                return ResourceManager.GetString("MainForm_MainForm_Load_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Honnan.
        /// </summary>
        internal static string MainForm_MainForm_Load_From {
            get {
                return ResourceManager.GetString("MainForm_MainForm_Load_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Csecsemő.
        /// </summary>
        internal static string MainForm_MainForm_Load_Infants {
            get {
                return ResourceManager.GetString("MainForm_MainForm_Load_Infants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oda-Vissza.
        /// </summary>
        internal static string MainForm_MainForm_Load_IsReturn {
            get {
                return ResourceManager.GetString("MainForm_MainForm_Load_IsReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utasok:.
        /// </summary>
        internal static string MainForm_MainForm_Load_Passangers {
            get {
                return ResourceManager.GetString("MainForm_MainForm_Load_Passangers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ár.
        /// </summary>
        internal static string MainForm_MainForm_Load_Price {
            get {
                return ResourceManager.GetString("MainForm_MainForm_Load_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keres.
        /// </summary>
        internal static string MainForm_MainForm_Load_Search {
            get {
                return ResourceManager.GetString("MainForm_MainForm_Load_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kereső.
        /// </summary>
        internal static string MainForm_MainForm_Load_SearchEngineName {
            get {
                return ResourceManager.GetString("MainForm_MainForm_Load_SearchEngineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Átszállások.
        /// </summary>
        internal static string MainForm_MainForm_Load_Stops {
            get {
                return ResourceManager.GetString("MainForm_MainForm_Load_Stops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jegyek.
        /// </summary>
        internal static string MainForm_MainForm_Load_TicketCount {
            get {
                return ResourceManager.GetString("MainForm_MainForm_Load_TicketCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hova.
        /// </summary>
        internal static string MainForm_MainForm_Load_To {
            get {
                return ResourceManager.GetString("MainForm_MainForm_Load_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oda.
        /// </summary>
        internal static string MainForm_MainForm_Load_ToDate {
            get {
                return ResourceManager.GetString("MainForm_MainForm_Load_ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Útidő.
        /// </summary>
        internal static string MainForm_MainForm_Load_TravelTime {
            get {
                return ResourceManager.GetString("MainForm_MainForm_Load_TravelTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leállítva.
        /// </summary>
        internal static string MainForm_resultCheck_Tick_Cancelled {
            get {
                return ResourceManager.GetString("MainForm_resultCheck_Tick_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kész.
        /// </summary>
        internal static string MainForm_resultCheck_Tick_Done {
            get {
                return ResourceManager.GetString("MainForm_resultCheck_Tick_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keres.
        /// </summary>
        internal static string MainForm_resultCheck_Tick_Search {
            get {
                return ResourceManager.GetString("MainForm_resultCheck_Tick_Search", resourceCulture);
            }
        }
    }
}
